#!/bin/bash
#
# customizepkg => modify PKGBUILD before building
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
# TODO:
#	PKGBUILD + file.install
#	auto patching feature
#

NAME=$(basename $0)
CONFIGDIR="/etc/${NAME}.d"
LOCALCONFIGDIR="${HOME}/.${NAME}"

# use colordiff if it's available
[[ $(type -p colordiff) ]] && DIFFCMD="colordiff -ub" || DIFFCMD="diff -ub"

usage() {
   echo -e	"A tool for Arch Linux to modify PKGBUILDs automatically.\n\n" \
			"usage: ${NAME} <option>\n" \
			"\n" \
			"${NAME}                shows a diff of changes that would be made\n" \
			"${NAME} --help,    -h  shows this help\n" \
			"${NAME} --modify,  -m  apply the modification in PKGBUILD file\n" \
			"${NAME} --vimdiff, -v  show diff between customised file and\n" \
			"                            original file with vimdiff\n" \
			"\n" \
			"configuration is read from:\n ~/.${NAME}/\${pkgname} or /etc/${NAME}.d/\${pkgname}\n" \
			"(see /etc/${NAME}.d/mplayer.example as an example)\n" \
			"\n" \
			"originally written by <wain@archlinux.fr>\n" \
			"+ modifications by ava1ar (customizepkg-new)\n" \
			"+ modifications by Steven Honeyman\n"
}

modify_file()
{
	local configfile=$1
	local originalscriptfile=$2
	local scriptfile=$3

	# if the customize file is executable, run it, then we're done.
	if [ -x "${configfile}" ]; then
		echo "=> ${configfile} is executable, so treating it as a script instead of config"
		"${configfile}" "${originalscriptfile}" "${scriptfile}" && return 0 || exit 1
	fi

	grep --invert-match "\(^#\|^$\)" ${configfile} |
	while IFS='#' read -r action context pattern value; do
		case ${action} in
			remove|replace)
				[[ ${action} == remove ]] && echo "=> removes '${pattern}' in ${context}" || echo "=> replaces '${pattern}' with '${value}' in ${context}"

				if [ "${action}" = "replace" -a "${context}" != "global" ]; then
					value="$(echo ${value} | tr -d "\'")"
				fi

				if [ "${context}" = "global" ]; then
					sed -i "s+${pattern}+${value}+g" "${scriptfile}"
				else
					[[ ${context} =~ depends$ ]] && pattern="${pattern}[<>=]*\(: \|\)[a-z0-9.{$}\-]*" # only need this for makedepends/optdepends/depends
					if [ "${action}" = "replace" ]; then
						case ${context} in
							prepare|build|package) sed -i "/^${context}() {/,/^}$/ s+${pattern}+${value}+g" "${scriptfile}" ;;
							*) sed -i "/^${context}=/,/)$/ s+${pattern}+${value}+g" "${scriptfile}" ;;
						esac
					else
						# remove the quotes if we're not replacing something
						sed -i "/^${context}=/,/)$/ s+[[:blank:]]*['\"]*${pattern}['\"]*+${value}+g" "${scriptfile}"
					fi
				fi
				;;
			removeline)
				echo "=> remove whole line containing '${pattern}' in ${context}"
				if [ "${context}" = "global" ]; then
					sed -i "/${pattern}/d" "${scriptfile}"
				else
					#pattern="${pattern}[<>=]*[a-z0-9.{$}]"
					sed -i "/^${context}() {/,/}$/ { /${pattern}/d }" "${scriptfile}"
				fi
				;;
			add)
				value="'$(echo ${pattern} | tr -d "\'")'"
				echo "=> adds ${value} in ${context}"
				# add the full line if it doesn't exist or just the value
				if grep --quiet "^${context}=" "${scriptfile}"; then
					sed -i "s+^${context}=(+&${value} +1" "${scriptfile}"
				else
					sed -i "/^pkgname/i${context}=(${value})" "${scriptfile}"
				fi
				;;
			*)
				echo "error: unknown action '${action}'" 1>&2
				;;
		esac
	done

	${DIFFCMD} "${originalscriptfile}" "${scriptfile}"
	return 0
}

################################################

MODIFY=0
while [ "$#" -ne "0" ]; do
	case $1 in
		-h|--help)
			usage
			exit 0
			;;
		-m|--modify)
			MODIFY=1
			;;
		--vimdiff|-v)
			[[ $(type -p vim) ]] && DIFFCMD="vim -d" || echo 'WARNING: vim was not found' 1>&2
			;;
	esac
	shift
done

if [ ! -r ./PKGBUILD ]; then
	echo 'PKGBUILD not found' 1>&2
	exit 1
fi

# use eval instead of creating a temp file to get pkgname etc
eval $(grep -e '^[[:blank:]]*pkg.*=' ./PKGBUILD)

# copy for modification
cp ./PKGBUILD ./PKGBUILD.custom

for package in "${pkgname[@]}"
do
	# local user prefs take priority
	if [ -r "${LOCALCONFIGDIR}/${package}" ]; then
		CONFIGDIR=${LOCALCONFIGDIR}
	elif [ ! -r "${CONFIGDIR}/${package}" ]; then
		echo "no configuration found for ${package} in ${LOCALCONFIGDIR}/ or ${CONFIGDIR}/"
		continue
	fi

	# copy the config file to current directory
	cp "${CONFIGDIR}/${package}" "./${package}.customize"

	#adding new files current dir from  ${CFGDIR}/${package} folder and including them to PKGBUILD
	if [ -d  "${CONFIGDIR}/${package}.files" ]; then
		# find checksum type used in PKGBUILD and utility to calculate the sum for added files
		checksum_context=$(grep -om 1 "^[a-z]*[0-9]*sums" "./PKGBUILD")
		checksum_utility=${checksum_context%?}
		echo "=> files from ${CONFIGDIR}/${package}.files will be included into package "
		for filepath in ${CONFIGDIR}/${package}.files/*; do
			if [[ -f ${filepath} ]]; then
				filename=$(basename ${filepath})
				echo -e "${filename}... \c"
				cp "${filepath}" ./${filename} 2> /dev/null
				if [[ $? -eq 0 ]];
					then
						echo "add#source#${filename}" >> ./${package}.customize
						echo "add#${checksum_context}#$(${checksum_utility} < ./${filename} | cut -d" " -f1)" >> ./${package}.customize
						echo 'included'
					else
						echo 'already exists. Skipping...'
				fi
				if [ ${MODIFY} -eq 0 ]; then
					rm ./${filename}
				fi
			fi
		done
	fi

	# make any changes to PKGBUILD.custom
	modify_file "./${package}.customize" "./PKGBUILD" "./PKGBUILD.custom" && rm -f "./${package}.customize" || exit 1
	if [ ${MODIFY} -eq 1 ]; then
		mv ./PKGBUILD ./PKGBUILD.original
		mv ./PKGBUILD.custom ./PKGBUILD
	else
		rm ./PKGBUILD.custom
	fi
done

exit 0
